/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Matricula.UI;

import Matricula.logic.Asignatura;
import Matricula.logic.Universidad;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author atenea
 */
public class AsignaturasUI extends javax.swing.JFrame {

    /**
     * Creates new form AsignaturasUI
     */
    private Universidad u;
    private ProgramacionAsignatura proAsi;

    public AsignaturasUI(Universidad u, ProgramacionAsignatura proAsi) {
        this.u = u;
        this.proAsi = proAsi;
        initComponents();
        ButtonSelect.addActionListener(new ListenereSelection());
        
        
        TableAsignaturas.setModel(new AbstractTableModel() {

            
            String[] names = {"nombre", "codigo", "creditos", "intensidad"};
            
            @Override
            public String getColumnName(int column) {
                return names[column];
            }

            @Override
            public int getRowCount() {
                if(u.getAsignaturas().isEmpty()){
                    return 0;
                }
                return u.getAsignaturas().size();
            }

            @Override
            public int getColumnCount() {
                return names.length;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                Asignatura asignatura = u.getAsignaturas().get(rowIndex);
                switch(columnIndex){
                    case 0: return asignatura.getNombre();
                    case 1: return asignatura.getCodigo();
                    case 2: return asignatura.getCreditos();
                    case 3: return asignatura.getIntensidad();
                        
                }
                return "";
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableAsignaturas = new javax.swing.JTable();
        ButtonSelect = new javax.swing.JButton();

        TableAsignaturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableAsignaturas);

        ButtonSelect.setText("Seleccionar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ButtonSelect)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonSelect)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSelect;
    private javax.swing.JTable TableAsignaturas;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public class ListenereSelection implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                if (TableAsignaturas.getSelectedRow() == -1) {
                    throw new Exception("Error no se ha selecionado ninguna asignatura");
                }
                Asignatura asigna = u.getAsignaturas().get(TableAsignaturas.getSelectedRow());
                proAsi.LoadAsignatura(asigna);
                setVisible(false);

            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }

        }

    }

}
