/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Matricula.UI;

import Matricula.logic.Curso;
import Matricula.logic.Periodo;
import Matricula.logic.Programa;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Polker
 */
public class CursosEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form CursosEstudiante
     */
    private Periodo periodo = null;
    private MatriculaUI matri;
    private Programa programa=null;
    public CursosEstudiante(Periodo periodo, MatriculaUI matri, Programa programa) {
        
        initComponents();
        this.matri = matri;
        this.periodo = periodo;
        this.programa = programa;
        this.ButtonSelected.addActionListener(new ListenerSelected());
        this.TableCursoStudent.setModel(new AbstractTableModel() {

            
            private String[] nombres = {"Codigo", "Nombre Asignatura", "Grupo", "Docente", "Creditos"};
            private List<Curso> cursos =periodo.cursosPrograma(programa);
            
            @Override
            public int getRowCount() {
                if(cursos.isEmpty()){
                    return 0;
                }
                return cursos.size();
            }

            @Override
            public int getColumnCount() {
                return nombres.length;
            }
            
            @Override
            public String getColumnName(int column){
                return nombres[column];
            }
            
            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                Curso curso = cursos.get(rowIndex);
                switch(columnIndex){
                    case 0:
                        return curso.getAsignatura().getCodigo();
                    case 1:
                        return curso.getAsignatura().getNombre();
                    case 2:
                        return curso.getGrupo();
                    case 3:
                        return curso.getDocente().getFullName();
                    case 4:
                        return curso.getAsignatura().getCreditos();
                }
                return "";
                
            }
            
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableCursoStudent = new javax.swing.JTable();
        ButtonSelected = new javax.swing.JButton();

        TableCursoStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableCursoStudent);

        ButtonSelected.setText("Seleccionar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonSelected)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonSelected)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSelected;
    private javax.swing.JTable TableCursoStudent;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
public class ListenerSelected implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            if(TableCursoStudent.getRowCount()!=0){
            Curso curso = periodo.cursosPrograma(programa).get(TableCursoStudent.getSelectedRow());
            matri.LoadMatricula(curso);
            TableCursoStudent.clearSelection();
            setVisible(false);
            }
        }
    
}

}
