/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Matricula.UI;

import Matricula.logic.Asignatura;
import Matricula.logic.Curso;
import Matricula.logic.Exceptions.ObjectNotFoundException;
import Matricula.logic.Universidad;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author atenea
 */
public class ProgramacionAsignatura extends javax.swing.JFrame {

    /**
     * Creates new form ProgramacionAsignatura
     */
    private Universidad u;
    private Asignatura asignatura;
    private List<Curso> cursosPrgramados = new ArrayList<>();
    private ProgramarCurso proCurso = null;
    private ProgramacionAsignatura proAsi = this;

    public ProgramacionAsignatura(Universidad u, ProgramarCurso proCurso) {
        initComponents();
        this.u = u;
        this.proCurso = proCurso;

        ProgramacionTableCursos.setModel(new AbstractTableModel() {

            String[] names = {"Codigo", "Nombre Asignatura", "Grupo", "Docente", "Creditos", "Estado"};

            @Override
            public String getColumnName(int ColumnIndex) {
                return names[ColumnIndex];
            }

            @Override
            public int getRowCount() {

                if (cursosPrgramados.isEmpty()) {
                    return 0;
                }
                return cursosPrgramados.size();
            }

            @Override
            public int getColumnCount() {
                return names.length;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                Curso curso = cursosPrgramados.get(rowIndex);
                switch (columnIndex) {
                    case 0:
                        return curso.getAsignatura().getCodigo();
                    case 1:
                        return curso.getAsignatura().getNombre();
                    case 2:
                        return curso.getGrupo();
                    case 3:
                        return curso.getDocente().getFullName();
                    case 4:
                        return curso.getAsignatura().getCreditos();
                    case 5:
                        return curso.getEstado();

                }
                return "";
            }
        });

    }

    public void LoadAsignatura(Asignatura asig) {
        try {
            this.asignatura = asig;
            AsignaturaCode.setText(asignatura.getCodigo());
            AsignaturaName.setText(asignatura.getNombre());
            AsignaturaName.setText(asignatura.getNombre());
            cursosPrgramados = u.programacionAsignatura(asignatura.getCodigo());
            ProgramacionTableCursos.updateUI();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ProgramacionButtonConsultar = new javax.swing.JButton();
        ButtonList = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProgramacionTableCursos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        AsignaturaCode = new javax.swing.JFormattedTextField();
        AsignaturaName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consulta de programacion de asignatura");

        jLabel2.setText("Codigo:");

        ProgramacionButtonConsultar.setText("Consultar");

        ButtonList.setText("...");

        ProgramacionTableCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ProgramacionTableCursos);

        jLabel3.setText("Nombre:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AsignaturaCode, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonList, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ProgramacionButtonConsultar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AsignaturaName, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ProgramacionButtonConsultar)
                    .addComponent(ButtonList)
                    .addComponent(AsignaturaCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AsignaturaName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        proCurso.setVisible(true);
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField AsignaturaCode;
    private javax.swing.JTextField AsignaturaName;
    private javax.swing.JButton ButtonList;
    private javax.swing.JButton ProgramacionButtonConsultar;
    private javax.swing.JTable ProgramacionTableCursos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public class ListenerBuscarAsignatura implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {

            try {
                asignatura = u.BuscarAsignatura(AsignaturaCode.getText().trim());
                LoadAsignatura(asignatura);
            } catch (ObjectNotFoundException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, ex.getMessage());

            }

        }
    }

        public class ListenerListaAsignaturas implements ActionListener {

            @Override
            public void actionPerformed(ActionEvent e) {
                new AsignaturasUI(u, proAsi).setVisible(true);

            }

        }
}
    
